# Generated by Django 5.2.4 on 2025-07-18 02:36

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='achievements',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='bio',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
